# %main% contains mirror site specific settings

[%main%]
root = /srv/www/
urlbase = /

!include includes/distro.ini
!include includes/os/**/*.ini
!include includes/app/**/*.ini
!include includes/font/**/*.ini