# %main% contains mirror site specific settings

[%main%]
root = /srv/www/
urlbase = /

!include includes/distro.ini

!include includes/os/alpine.ini
!include includes/os/archlinux.ini
!include includes/os/fedora.ini
!include includes/os/kali.ini
!include includes/os/opensuse.ini
!include includes/os/debian.ini
!include includes/os/deepin.ini
!include includes/os/centos.ini
!include includes/os/ubuntu.ini
#!include includes/os/ubuntukylin.ini
!include includes/os/linux_mint.ini
!include includes/os/wsl-distributions.ini


!include includes/app/msys2.ini
!include includes/app/mingw-w64.ini
!include includes/app/openjdk.ini
!include includes/app/python.ini
!include includes/app/adoptium.ini

!include includes/app/wsl.ini
!include includes/app/etcher.ini
!include includes/app/zerotier.ini
!include includes/app/kicad.ini
!include includes/app/tex.ini

!include includes/app/blender.ini
!include includes/app/vlc.ini
!include includes/app/obs.ini

!include includes/app/office-tool.ini
!include includes/app/one_kvm.ini
!include includes/app/escrcpy.ini
!include includes/app/inkeys.ini
!include includes/app/micyou.ini
!include includes/app/classisland.ini


!include includes/font/smiley-sans.ini
!include includes/font/lxgwWenKai.ini
