[google fonts]
distro = Google Fonts
location = github-release/googlefonts/*/*/*
# This pattern matches all ZIP files except those in LatestRelease, and has special treatment for names of recent Noto CJK releases.
# https://regex101.com/r/aPUKIG/1
pattern = googlefonts/(noto-\w+)/(?!LatestRelease)(?:Noto (Sans|Serif) CJK Version ([.\d]+) \(.+\)|.*)/(.+\.zip)
# For Noto CJK, the file name ($4) already contains Sans/Serif ($2). However, Sans and Serif are versioned separately. To avoid confusion, we put Sans/Serif before the version number ($3) even though it is redundant.
version = $1 $2 $3 $4
category = font

[googlefonts noto cjk]
distro = Google Fonts
category = font
location = github-release/googlefonts/noto-cjk/LatestRelease/*
pattern = repo-snapshot.tar.gz
version = noto-cjk repo-snapshot
platform = tar.gz

[googlefonts noto emoji]
distro = Google Fonts
category = font
location = github-release/googlefonts/noto-emoji/LatestRelease/*
pattern = repo-snapshot.tar.gz
version = noto-emoji repo-snapshot
platform = tar.gz

[googlefonts noto fonts]
distro = Google Fonts
category = font
location = github-release/googlefonts/noto-fonts/LatestRelease/*
pattern = repo-snapshot.tar.gz
version = noto-fonts repo-snapshot
platform = tar.gz

