[Adoptium-JDK]
distro = Adoptium Temurin
#listvers = 1
location = adoptium/*/jdk/*/*/*
#pattern = /OpenJDK([0-9]+).+_([^_]+)_([^_]+)_[^_]+_([0-9.]+)_([0-9]+)\.(.+)
pattern = /OpenJDK([0-9]+).+_(x64|x86-32|aarch64|arm)_(linux|windows|macos|mac)_[^_]+_([0-9.]+)_([0-9]+)\.(.+)
platform = $3-$2-JDK
type = $6
#version = $1-$4-$5
version = $1
category = app
[Adoptium-JRE]
distro = Adoptium Temurin
#listvers = 1
location = adoptium/*/jre/*/*/*
#pattern = /OpenJDK([0-9]+).+_([^_]+)_([^_]+)_[^_]+_([0-9.]+)_([0-9]+)\.(.+)
pattern = /OpenJDK([0-9]+).+_(x64|x86-32|aarch64|arm)_(linux|windows|macos|mac)_[^_]+_([0-9.]+)_([0-9]+)\.(.+)
platform = $3-$2-JRE
type = $6
#version = $1-$4-$5
version = $1
category = app
