[openjdk-bigver]
distro = OpenJDK
#listvers = 3
location = openjdk/*/openjdk-*
pattern = /openjdk-([0-9]+)_([a-z]+)-([a-z0-9]+)_bin\.(tar\.gz|zip)
platform = $2-$3
type = $4
version = $1
category = app
[openjdk-smallver]
distro = OpenJDK
listvers = 2
location = openjdk/*/openjdk-*
pattern = /openjdk-([0-9]+\.[0-9.]+)_([a-z]+)-([a-z0-9]+)_bin\.(tar\.gz|zip)
platform = $2-$3
type = $4
version = $1
category = app
