name: test
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check code format
        run: |
          pip install black
          black --check --exclude version.py .
      - name: Check config sanity
        run: python3 utils/check-config.py includes/
